opt: adamw
lr: 0.01
conv1_channel: 10
conv1_kernel_size: 3
conv1_stride: 3
maxpool1_kernel_size: 8
maxpool1_stride: 2
conv2_channel: 15
conv2_kernel_size: 5
conv2_stride: 1
maxpool2_kernel_size: 8
maxpool2_stride: 1
drop_1: 0.5
conv3_channel: 5
conv3_kernel_size: 3
conv3_stride: 2
avgpool1_kernel_size: 6
avgpool1_stride: 1
drop_2: 0.3
conv4_channel: 10
conv4_kernel_size: 5
conv4_stride: 3
avgpool2_kernel_size: 6
avgpool2_stride: 1
conv5_channel: 20
conv5_kernel_size: 9
conv5_stride: 1
drop_3: 0.3
