opt: adamw
lr: 0.01
conv1_channel: 10
conv1_kernel_size: 9
conv1_stride: 4
maxpool1_kernel_size: 2
maxpool1_stride: 1
conv2_channel: 15
conv2_kernel_size: 9
conv2_stride: 2
maxpool2_kernel_size: 4
maxpool2_stride: 1
drop_1: 0.3
conv3_channel: 15
conv3_kernel_size: 7
conv3_stride: 1
avgpool1_kernel_size: 4
avgpool1_stride: 4
drop_2: 0.6
conv4_channel: 15
conv4_kernel_size: 3
conv4_stride: 3
avgpool2_kernel_size: 4
avgpool2_stride: 1
conv5_channel: 15
conv5_kernel_size: 3
conv5_stride: 4
drop_3: 0.4
