opt: adam
lr: 0.005
scc_1_temp_chan: 20
scc_1_ksize: 0.2
scc_1_pool_size: 0.4
scc_1_pool_stride: 0.3
scc_1_drop_rate: 0.4
scc_2_temp_chan: 10
scc_2_ksize: 0.6
scc_2_pool_size: 0.4
scc_2_pool_stride: 0.1
scc_2_drop_rate: 0.3
eeg_1_eeg_ksize: 0.2
eeg_1_filter_1: 4
eeg_1_filter_2: 32
eeg_1_filter_3: 32
eeg_1_pool_kernel_1: 2
eeg_1_pool_stride_1: 6
eeg_1_pool_kernel_2: 4
eeg_1_pool_stride_2: 8
eeg_1_drop_1: 0.5
eeg_1_drop_2: 0.4
eeg_2_eeg_ksize: 0.2
eeg_2_filter_1: 8
eeg_2_filter_2: 32
eeg_2_filter_3: 32
eeg_2_pool_kernel_1: 8
eeg_2_pool_stride_1: 6
eeg_2_pool_kernel_2: 6
eeg_2_pool_stride_2: 2
eeg_2_drop_1: 0.3
eeg_2_drop_2: 0.4
emb_size: 8
drop_linear: 0.6
