opt: sgd
lr: 0.005
conv_channel_1: 16
conv_kernel_1: 7
conv_stride_1: 2
pool_kernel_1: 6
pool_stride_1: 1
conv_channel_2: 16
conv_kernel_2: 5
conv_stride_2: 1
pool_kernel_2: 8
pool_stride_2: 2
conv_channel_3: 16
conv_kernel_3: 7
conv_stride_3: 2
pool_kernel_3: 2
pool_stride_3: 1
conv_channel_4: 64
conv_kernel_4: 3
conv_stride_4: 2
pool_kernel_4: 4
pool_stride_4: 1
fc_1: 64
fc_2: 64
