opt: adam
lr: 0.01
conv_channel_1: 32
conv_kernel_1: 7
conv_stride_1: 1
pool_kernel_1: 2
pool_stride_1: 3
conv_channel_2: 32
conv_kernel_2: 7
conv_stride_2: 1
pool_kernel_2: 8
pool_stride_2: 3
conv_channel_3: 128
conv_kernel_3: 7
conv_stride_3: 1
pool_kernel_3: 4
pool_stride_3: 2
conv_channel_4: 64
conv_kernel_4: 7
conv_stride_4: 4
pool_kernel_4: 2
pool_stride_4: 2
fc_1: 16
fc_2: 8
