opt: adamw
lr: 0.0005
patch_embed_d_model: 32
patch_len: 32
patch_stride: 64
patch_drop: 0.4
encoder_d_model: 32
encoder_1_drop: 0.2
encoder_1_n_heads: 2
encoder_1_diff: 128
encoder_1_dropout: 0.3
drop_1: 0.4
encoder_2_drop: 0.3
encoder_2_n_heads: 4
encoder_2_diff: 64
encoder_2_dropout: 0.1
drop_2: 0.5
encoder_3_drop: 0.3
encoder_3_n_heads: 6
encoder_3_diff: 64
encoder_3_dropout: 0.4
drop_3: 0.3
encoder_4_drop: 0.2
encoder_4_n_heads: 4
encoder_4_diff: 512
encoder_4_dropout: 0.3
drop_4: 0.4
knn: 32
graph_embed_dim: 16
spatial_1_drop: 0.4
spatial_1_n_heads: 8
spatial_1_diff: 512
spatial_1_dropout: 0.1
spatial_2_drop: 0.4
spatial_2_n_heads: 6
spatial_2_diff: 512
spatial_2_dropout: 0.1
spatial_3_drop: 0.1
spatial_3_n_heads: 6
spatial_3_diff: 512
spatial_3_dropout: 0.2
spatial_4_drop: 0.4
spatial_4_n_heads: 4
spatial_4_diff: 512
spatial_4_dropout: 0.1
dropout: 0.3
